# Javascript Node CircleCI 2.0 configuration file
#
# Check {{ '/language-javascript' | docs_url }} for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.18.1

    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    docker:
      - image: cimg/node:14.18.1

    working_directory: ~/repo
    steps:
      - checkout

      - run: npm test

  deploy:
    docker:
      - image: cimg/node:14.18.1

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Set registry
          command: npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish --access public
      - run:
          name: Publish on Spot
          working_directory: ~/repo
          command: npx @kelsus/api-spot-package --environment=prod --serviceType=package --repoUrl=https://github.com/Kelsus/api-spot-package --serviceUrl=https://www.npmjs.com/package/@kelsus/api-spot-package

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - main
